name: Deploy CloudFormation

on:
  workflow_dispatch:
    inputs:
      template:
        description: 'Template to deploy'
        type: choice
        required: true
        options:
          - VPC-BasicNetworking

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ github.event.inputs.template }}
          template: templates/${{ github.event.inputs.template }}.yaml
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: '1'
