---
name: Manage CloudFormation

on:
  workflow_dispatch:
    inputs:
      template:
        description: 'Template to deploy or delete'
        type: choice
        required: true
        options:
          - VPC-3Public3Private
          - EC2-Ansible
          - EC2-Bastion
          - ALL
      environment:
        description: 'Deployment environment'
        type: choice
        required: true
        options:
          - general
          - production
          - development
      action:
        description: 'Action to perform'
        type: choice
        required: true
        options:
          - deploy
          - delete

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select AWS account
        run: |
          if [ "${{ github.event.inputs.environment }}" = "general" ]; then
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_GENERAL }}" >> "$GITHUB_ENV"
          elif [ "${{ github.event.inputs.environment }}" = "production" ]; then
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_PRODUCTION }}" >> "$GITHUB_ENV"
          elif [ "${{ github.event.inputs.environment }}" = "development" ]; then
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_DEVELOPMENT }}" >> "$GITHUB_ENV"
          else
            echo "Unknown environment: ${{ github.event.inputs.environment }}" >&2
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation stack
        if: ${{ github.event.inputs.action == 'deploy' }}
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ github.event.inputs.template }}
          template: templates/${{ github.event.inputs.template }}.yaml
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: '1'

      - name: Delete CloudFormation stack
        if: ${{ github.event.inputs.action == 'delete' && github.event.inputs.template != 'ALL' }}
        run: |
          aws cloudformation delete-stack --stack-name ${{ github.event.inputs.template }}
          aws cloudformation wait stack-delete-complete --stack-name ${{ github.event.inputs.template }}

      - name: Delete all CloudFormation stacks
        if: ${{ github.event.inputs.action == 'delete' && github.event.inputs.template == 'ALL' }}
        run: |
          for template_file in templates/*.yaml; do
            stack_name=$(basename "$template_file" .yaml)
            aws cloudformation delete-stack --stack-name "$stack_name"
            aws cloudformation wait stack-delete-complete --stack-name "$stack_name"
          done
